name: Deploy ASP.NET Backend to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # or whatever your backend uses

      - name: Restore dependencies
        run: dotnet restore ./backend/Intex.API/Intex.API.csproj

      - name: Build
        run: dotnet build ./backend/Intex.API/Intex.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./backend/Intex.API/Intex.API.csproj --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: CineNiche-INTEX
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
